apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
      app: {{ .Values.appName }}
  type: {{ .Values.serviceType }}
  ports:
    - name: {{ .Values.portName }}
      protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      
